### ISSUE TITLE
ErrorResponse type doesn't extend ApolloError and it's not exported

### ISSUE THREAD

**Issue by LauraBeatris** [jungsoft/apollo-sentry-helper#17]
There's a type error when passing an error of ``ApolloError`` type to the ``getErrorsList`` function 

![image](https://user-images.githubusercontent.com/48022589/90282089-2a79f700-de44-11ea-99c0-072f0462422f.png)

![image](https://user-images.githubusercontent.com/48022589/90282129-3960a980-de44-11ea-9856-04fafdcc9392.png)

--- 

The ``ErrorResponse`` should be exported within the package.

**Comment by pedro-lb** [comment]
Published in https://github.com/jungsoft/apollo-sentry-helper/releases/tag/2.0.2 =)
